version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: swiftride-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftride
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: swiftride-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: swiftride-backend
    env_file:
      - ../apps/backend/.env
    depends_on:
      - db
      - minio
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: swiftride-frontend
    env_file:
      - ../apps/frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  minio_data:
