
name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Frontend to Railway
        uses: railwayapp/railway-action@v1
        with:
          serviceId: ${{ secrets.RAILWAY_FRONTEND_SERVICE_ID }}
          apiToken: ${{ secrets.RAILWAY_API_TOKEN }}
          rootDirectory: apps/frontend

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Backend to Railway
        uses: railwayapp/railway-action@v1
        with:
          serviceId: ${{ secrets.RAILWAY_BACKEND_SERVICE_ID }}
          apiToken: ${{ secrets.RAILWAY_API_TOKEN }}
          rootDirectory: apps/backend
