name: CI - Build Backend & Frontend

on:
  push:
    branches: ["master", "develop"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: swiftride
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------
      # Backend setup
      # -----------------------
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: apps/backend/package-lock.json

      - name: Install Backend Deps
        working-directory: ./apps/backend
        run: npm ci

      - name: Build Backend
        working-directory: ./apps/backend
        run: npm run build

      - name: Test Backend
        working-directory: ./apps/backend
        run: npm run test --if-present

      - name: Build Backend Docker image
        run: docker build -t swiftride-backend ./apps/backend

      # -----------------------
      # Frontend setup
      # -----------------------
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install Frontend Deps
        working-directory: ./apps/frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./apps/frontend
        run: npm run build

      - name: Build Frontend Docker image
        run: docker build -t swiftride-frontend ./apps/frontend
